"""
Context Compression Engine — Multi-Layer Evolved Context Compression

Standalone core module implementing a 3-layer memory compression system.

Architecture:
    Layer 0 (Short-term): Sub-layers per interaction turn
        - Focus, user preferences, query, context metadata
        - Generated by model, extracted from response
        - One new sub-layer per interaction

    Layer 1 (Medium-term): Compressed conversation summary
        - Generated via LLM compression of N sub-layer-0 entries
        - Triggered at configurable turn threshold (default: 10)

    Layer 2 (Medium/Long-term): Deep compressed persistent memory
        - Generated alongside Layer 1 during compression cycles

Features:
    - Separate compression profiles for chat and agent_loop
    - LLM provider resolved via ProviderMapper (role-based chain)
    - Configurable thresholds via env vars (UBP_CONTEXT_COMPRESSION__*)
    - Comprehensive logging for debug and testing
    - Standalone — no external module dependencies required

3-File Pattern:
    - __init__.py: Entry point (this file)
    - adapter.py: UBP framework bridge (BaseHybridModule)
    - providers.py: Pure business logic (zero framework deps)
    - models.py: Pydantic data models

v1.0.0 — Initial implementation
"""

from pathlib import Path

from .adapter import ContextCompressionEngineAdapter
from .models import (
    CompressionEngineConfig,
    CompressionMode,
    CompressionResult,
    CompressionState,
    Layer0State,
    Layer1,
    Layer2,
    ProfileType,
    SubLayer0,
    CompressionProfileSettings,
)
from .providers import ContextCompressionProvider

__version__ = "1.0.0"

__all__ = [
    "ContextCompressionEngineAdapter",
    "ContextCompressionProvider",
    "CompressionEngineConfig",
    "CompressionMode",
    "CompressionResult",
    "CompressionState",
    "Layer0State",
    "Layer1",
    "Layer2",
    "ProfileType",
    "SubLayer0",
    "CompressionProfileSettings",
    "create_module",
]


def create_module(module_path: Path, **kwargs) -> ContextCompressionEngineAdapter:
    """
    Factory function to create module instance.

    Args:
        module_path: Path to module directory
        **kwargs: Additional arguments (event_bus, di_container)

    Returns:
        Initialized ContextCompressionEngineAdapter instance
    """
    return ContextCompressionEngineAdapter(module_path, **kwargs)
