"""
Context Compression Engine — Pydantic Models

Multi-layer evolved context compression data structures.

Layer Architecture:
    Layer 0 (Short-term): Sub-layers per interaction turn
        - Focus, user preferences, query, context metadata
        - Generated by model, extracted from response
        - One new sub-layer per interaction

    Layer 1 (Medium-term): Compressed conversation summary
        - Conversation focus, rules, user-specific requests
        - Generated via LLM compression of N sub-layer-0 entries
        - Triggered at configurable turn threshold

    Layer 2 (Medium/Long-term): Deep compressed memory
        - High-level patterns, persistent user traits, topic arcs
        - Generated alongside Layer 1 during compression cycles

v1.0.0 — Initial implementation
"""

from __future__ import annotations

import time
import uuid
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class CompressionMode(str, Enum):
    """How compression was triggered."""
    NONE = "none"
    THRESHOLD = "threshold"          # Triggered by sub-layer count threshold
    MANUAL = "manual"                # Explicitly requested
    EMERGENCY = "emergency"          # Context window pressure


class LayerType(str, Enum):
    """Memory layer classification."""
    LAYER_0 = "layer_0"             # Short-term (sub-layers)
    LAYER_1 = "layer_1"             # Medium-term (compressed)
    LAYER_2 = "layer_2"             # Medium/Long-term (deep compressed)


class ProfileType(str, Enum):
    """Profile type for parameter selection."""
    CHAT = "chat"                    # Standard chat client
    AGENT_LOOP = "agent_loop"       # MCP agent loop


# ---------------------------------------------------------------------------
# Layer 0: Sub-Layer (Short-Term Memory)
# ---------------------------------------------------------------------------

class SubLayer0(BaseModel):
    """
    Single sub-layer of Layer 0 (short-term memory).

    Generated by the model at each interaction turn.
    Contains focused context snapshot for the current query.
    """
    sub_layer_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    turn_number: int = Field(..., ge=0, description="Interaction turn that generated this sub-layer")
    timestamp: float = Field(default_factory=time.time)

    # Core context fields
    focus: str = Field(..., description="Current focus/intent of the user query")
    user_preferences: Dict[str, Any] = Field(
        default_factory=dict,
        description="User preferences detected in this turn",
    )
    query_summary: str = Field(..., description="Condensed representation of the user query")
    query_type: str = Field(
        default="general",
        description="Classification of the query (e.g., question, command, follow-up)",
    )

    # Contextual metadata
    entities_mentioned: List[str] = Field(
        default_factory=list,
        description="Key entities referenced in this turn",
    )
    topic: str = Field(default="", description="Detected topic of the interaction")
    sentiment: str = Field(default="neutral", description="Detected sentiment")
    language: str = Field(default="auto", description="Detected language")

    # Response metadata
    response_quality_signals: Dict[str, Any] = Field(
        default_factory=dict,
        description="Quality signals from the model response",
    )

    # Free-form extension
    extra: Dict[str, Any] = Field(
        default_factory=dict,
        description="Additional model-generated context data",
    )


class Layer0State(BaseModel):
    """
    Complete Layer 0 state — ordered list of sub-layers.

    Represents the short-term memory window for a session.
    """
    session_id: str = Field(..., description="Owning session identifier")
    sub_layers: List[SubLayer0] = Field(default_factory=list)
    max_sub_layers: int = Field(
        default=50,
        description="Maximum sub-layers to retain before oldest are dropped",
    )

    @property
    def count(self) -> int:
        return len(self.sub_layers)

    @property
    def latest(self) -> Optional[SubLayer0]:
        return self.sub_layers[-1] if self.sub_layers else None

    def add_sub_layer(self, sub_layer: SubLayer0) -> None:
        """Add a sub-layer, enforcing max capacity."""
        self.sub_layers.append(sub_layer)
        if len(self.sub_layers) > self.max_sub_layers:
            self.sub_layers = self.sub_layers[-self.max_sub_layers:]

    def get_range(self, start: int, end: Optional[int] = None) -> List[SubLayer0]:
        """Get sub-layers by turn range (inclusive)."""
        return [
            sl for sl in self.sub_layers
            if sl.turn_number >= start and (end is None or sl.turn_number <= end)
        ]


# ---------------------------------------------------------------------------
# Layer 1: Medium-Term Memory (Compressed)
# ---------------------------------------------------------------------------

class Layer1(BaseModel):
    """
    Layer 1 — medium-term compressed memory.

    Generated by LLM compression of N sub-layer-0 entries.
    Captures conversation-level patterns and user directives.
    """
    layer_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    session_id: str = Field(..., description="Owning session identifier")
    timestamp: float = Field(default_factory=time.time)
    version: int = Field(default=1, description="Incremented on each re-compression")

    # Compressed from sub-layers
    source_turn_range: List[int] = Field(
        default_factory=list,
        description="[start_turn, end_turn] of the sub-layers that were compressed",
    )
    source_sub_layer_count: int = Field(default=0)

    # Core compressed fields
    conversation_focus: str = Field(
        ..., description="High-level focus/theme of the conversation so far"
    )
    user_rules: List[str] = Field(
        default_factory=list,
        description="Explicit rules or constraints requested by the user",
    )
    user_specific_requests: List[str] = Field(
        default_factory=list,
        description="Specific requests/instructions from the user across turns",
    )
    conversation_description: str = Field(
        ..., description="Narrative description of the conversation flow"
    )
    key_topics: List[str] = Field(
        default_factory=list,
        description="Main topics discussed",
    )
    aggregated_preferences: Dict[str, Any] = Field(
        default_factory=dict,
        description="Merged user preferences across compressed sub-layers",
    )
    key_entities: List[str] = Field(
        default_factory=list,
        description="Important entities across the compressed window",
    )
    language: str = Field(default="auto", description="Primary conversation language")

    # Compression metadata
    compression_mode: CompressionMode = Field(default=CompressionMode.THRESHOLD)
    compression_model: str = Field(default="", description="Model used for compression")
    compression_provider: str = Field(default="", description="Provider used for compression")
    compression_tokens_in: int = Field(default=0, description="Input tokens to compression")
    compression_tokens_out: int = Field(default=0, description="Output tokens from compression")
    compression_ratio: float = Field(default=0.0, description="tokens_out / tokens_in")
    compression_latency_ms: float = Field(default=0.0)


# ---------------------------------------------------------------------------
# Layer 2: Medium/Long-Term Memory (Deep Compressed)
# ---------------------------------------------------------------------------

class Layer2(BaseModel):
    """
    Layer 2 — medium/long-term deep compressed memory.

    Generated alongside Layer 1 during compression cycles.
    Captures persistent patterns, user profile evolution, and topic arcs.
    """
    layer_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    session_id: str = Field(..., description="Owning session identifier")
    timestamp: float = Field(default_factory=time.time)
    version: int = Field(default=1, description="Incremented on each update")

    # Deep compressed fields
    session_summary: str = Field(
        ..., description="Ultra-concise summary of the entire session"
    )
    persistent_user_traits: Dict[str, Any] = Field(
        default_factory=dict,
        description="Long-lasting user characteristics observed",
    )
    topic_arc: List[str] = Field(
        default_factory=list,
        description="Ordered list of major topic transitions",
    )
    interaction_patterns: Dict[str, Any] = Field(
        default_factory=dict,
        description="Observed interaction patterns (verbosity, question style, etc.)",
    )
    accumulated_knowledge: List[str] = Field(
        default_factory=list,
        description="Key facts established during the conversation",
    )
    unresolved_threads: List[str] = Field(
        default_factory=list,
        description="Topics or questions left open",
    )

    # Compression metadata
    source_layer1_versions: List[int] = Field(
        default_factory=list,
        description="Layer 1 versions that contributed to this Layer 2",
    )
    total_turns_compressed: int = Field(default=0)
    compression_model: str = Field(default="")
    compression_provider: str = Field(default="")


# ---------------------------------------------------------------------------
# Composite State
# ---------------------------------------------------------------------------

class CompressionState(BaseModel):
    """
    Full compression state for a session.

    Aggregates all three layers into a single serialisable snapshot.
    """
    session_id: str
    layer_0: Layer0State
    layer_1: Optional[Layer1] = None
    layer_2: Optional[Layer2] = None
    total_compressions: int = Field(default=0, description="Number of compression cycles executed")
    last_compression_turn: int = Field(default=-1, description="Turn at which last compression ran (-1 = never compressed)")


# ---------------------------------------------------------------------------
# Compression Result
# ---------------------------------------------------------------------------

class CompressionResult(BaseModel):
    """Result of a compression operation."""
    success: bool
    layer_1: Optional[Layer1] = None
    layer_2: Optional[Layer2] = None
    sub_layers_consumed: int = Field(default=0)
    compression_mode: CompressionMode = Field(default=CompressionMode.NONE)
    error: Optional[str] = None
    latency_ms: float = Field(default=0.0)


# ---------------------------------------------------------------------------
# Configuration Models
# ---------------------------------------------------------------------------

class CompressionProfileSettings(BaseModel):
    """
    Per-profile compression parameters.

    Separate settings for 'chat' (end-user) and 'agent_loop' (MCP agent).
    """
    compression_trigger_threshold: int = Field(
        default=10,
        ge=2,
        description="Number of sub-layer-0 entries that trigger compression",
    )
    max_sub_layers_retained: int = Field(
        default=50,
        ge=5,
        description="Maximum sub-layers kept in Layer 0",
    )
    compression_model_role: str = Field(
        default="enrichment",
        description="ProviderMapper role used to resolve compression LLM",
    )
    layer1_max_tokens: int = Field(
        default=800,
        description="Target token budget for Layer 1 output",
    )
    layer2_max_tokens: int = Field(
        default=400,
        description="Target token budget for Layer 2 output",
    )
    include_layer2: bool = Field(
        default=True,
        description="Whether to generate Layer 2 during compression",
    )


def _default_agent_loop_profile() -> CompressionProfileSettings:
    """Default profile settings for agent_loop."""
    return CompressionProfileSettings(
        compression_trigger_threshold=8,
        max_sub_layers_retained=30,
        layer1_max_tokens=600,
        layer2_max_tokens=300,
    )


class CompressionEngineConfig(BaseModel):
    """
    Top-level configuration for the Context Compression Engine.

    Loaded from config.json with env-var interpolation.
    """
    enabled: bool = True
    log_level: str = Field(default="INFO", description="Module-specific log level")

    # Per-profile settings
    chat_profile: CompressionProfileSettings = Field(
        default_factory=CompressionProfileSettings,
    )
    agent_loop_profile: CompressionProfileSettings = Field(
        default_factory=_default_agent_loop_profile,
    )

    # Provider override (takes precedence over role resolution)
    compression_provider_override: Optional[str] = Field(
        default=None,
        description="Force a specific provider (e.g. 'vllm') instead of role resolution",
    )
    compression_model_override: Optional[str] = Field(
        default=None,
        description="Force a specific model name",
    )

    def get_profile(self, profile_type: ProfileType) -> CompressionProfileSettings:
        """Return settings for the given profile type."""
        if profile_type == ProfileType.AGENT_LOOP:
            return self.agent_loop_profile
        return self.chat_profile
